# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqPoH7lg2sHv9cM0IsSQtibyABRziasi
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
kom=cv2.imread("kom.jpg")
cv2_imshow(kom)

oqqora=cv2.cvtColor(kom,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
kom=cv2.imread("kom.jfif")
cv2_imshow(kom)

oqqora=cv2.cvtColor(kom,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
kon=cv2.imread("kon.png")
cv2_imshow(kon)

oqqora=cv2.cvtColor(kon,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
komb=cv2.imread("komb.jfif")
cv2_imshow(komb)

oqqora=cv2.cvtColor(komb,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)